package com.miaoshaproject.dao;

import com.miaoshaproject.dataobjcet.ItemStockDao;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int insert(ItemStockDao record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int insertSelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    ItemStockDao selectByPrimaryKey(Integer id);
    ItemStockDao selectByItemId(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ItemStockDao record);
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(ItemStockDao record);
}