package com.miaoshaproject.dao;

import com.miaoshaproject.dataobjcet.ItemDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);
    List<ItemDao>  listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int insert(ItemDao record);
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int insertSelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    ItemDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jun 14 20:02:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(ItemDao record);
}