package com.miaoshaproject.dao;

import com.miaoshaproject.dataobjcet.PromoDao;

public interface PromoDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 16 12:32:07 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 16 12:32:07 GMT+08:00 2019
     */
    int insert(PromoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 16 12:32:07 GMT+08:00 2019
     */
    int insertSelective(PromoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 16 12:32:07 GMT+08:00 2019
     */
    PromoDao selectByPrimaryKey(Integer id);
    PromoDao selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 16 12:32:07 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(PromoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 16 12:32:07 GMT+08:00 2019
     */
    int updateByPrimaryKey(PromoDao record);
}