package com.miaoshaproject.dao;

import com.miaoshaproject.dataobjcet.UserDao;

public interface UserDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);
    UserDao selectByTelephone(String telephone);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int insert(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int insertSelective(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    UserDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int updateByPrimaryKey(UserDao record);
}