package com.miaoshaproject.dao;

import com.miaoshaproject.dataobjcet.UserPasswordDao;

public interface UserPasswordDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int insert(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int insertSelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    UserPasswordDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    UserPasswordDao selectByUserId(Integer userid);

    int updateByPrimaryKeySelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 11 21:13:54 GMT+08:00 2019
     */
    int updateByPrimaryKey(UserPasswordDao record);
}